[package]
name = "archdiff"
version = "0.1.0"
authors = ["Naitik Shah <n@daaku.org>"]
edition = "2018"

[dependencies]
alpm = "2.1"
anyhow = "1.0"
ignore = "0.4"
log = "0.4"
pretty_env_logger = "0.4"
rayon = "1.5"
structopt = "0.3"
walkdir = "2.3"
